name: gesabscences
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0
  path_provider: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  file_picker: ^10.1.9 
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
